### ISSUE TITLE
Add an IT test to check the AdminView

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/bookstore-starter-flow#121]
The pull request https://github.com/vaadin/bookstore-starter-flow/pull/120 has an AdminView page not working due to https://github.com/vaadin/flow/issues/5509 but its IT tests are passing.

Need to add another test that will detect the issue and won't allow to merge such PRs.

**Comment by pleku** [comment]
We don't currently have any ITs due to not being able to use TB on this.
