### ISSUE TITLE
Application is broken

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/bookstore-starter-flow#152]
- Build and run application as readme says
- open `http://localhost:8080/`

Result: you are redirected immediately to `http://localhost:8080/Inventory/` without asking login first.
Since there is no auth info the page shows nothing except a need to login.

**Comment by caalador** [comment]
This seems to also get missmatching component versions: `Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry`
