### ISSUE TITLE
Opening ProductForm via New Product button and then clicking Logout causes StackOverflowError

### ISSUE THREAD

**Issue by ujoni** [vaadin/bookstore-starter-flow#85]
**Steps to reproduce:**
- Login in as Admin
- Close PWA popup
- Click "New product" button
- Click "Logout" button

**Expected:**
- Application logs out the user

**Actual:**
- Application crashes with `StackOverflowError`

This can also be replicated by refreshing the page while New product form is open.

**Comment by pleku** [comment]
Fix ought to be picked to both V10 and V12 branches of the starter
